disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - variable_name
  - type_name
  - force_cast
  - todo
  - legacy_constructor
  - function_body_length
  - type_body_length
